apiVersion: v1
kind: Service
metadata:
  name: service-java-hello-world
spec:
  type: LoadBalancer
  selector:
    project: java-hello-world
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

