apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nginx-workload-admin
subjects:
  - kind: ServiceAccount    
    name: nginx
    namespace: default
  - kind: User
    name: robert
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: workload-admin
  apiGroup: rbac.authorization.k8s.io