apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deployment
spec:
    replicas: 3
    strategy:
      type: Recreate
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
                company: teknei
        spec:
            containers:
            - name: nginx
              image: nginx:1.19
              ports:
              - containerPort: 80
