apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deployment
spec:
    replicas: 1
    strategy:
      type: Recreate
    selector:
        matchLabels:
            app: nginx    
    template:
        metadata:
            labels:
                app: nginx
                company: teknei
        spec:
            initContainers:
              - name: hello
                image: ubuntu
                command:
                - /bin/bash
                args:
                - -c
                - "echo Hello Teknei && sleep 5 && date"
            containers:
            - name: nginx
              image: nginx:1.19
              ports:
              - containerPort: 80
              volumeMounts:
                - mountPath: /root/config
                  name: config
                - mountPath: /root/credentials
                  name: credentials
                # - mountPath: /root/persistent
                #   name: data
              resources:
                requests:
                  cpu: 0.1
                  memory: 128M
                limits:
                  cpu: 0.1
                  memory: 128M 
   
            volumes:
            - name: config
              configMap:
                name: nginx-config
            - name: credentials
              secret:
                secretName: nginx-secret
            # - name: data
            #   persistentVolumeClaim:
            #     claimName: nginx-pvc
            # tolerations:
            # - key: "fastcpu"
            #   operator: "Exists"
            #   effect: "NoSchedule"
            serviceAccountName: nginx
              