apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: nginx-statefulset
spec:
    selector:
        matchLabels:
            app: nginx-statefulset
    serviceName: nginx-statefulset
    replicas: 3
    template:
        metadata:
            labels:
                app: nginx-statefulset
        spec:
            containers:
            - name: nginx
              image: nginx
              ports:
              - containerPort: 80
              volumeMounts:
                - mountPath: /root/persistent
                  name: nginx-statefulset
    volumeClaimTemplates:
    - metadata:
        name: nginx-statefulset
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi