apiVersion: apps/v1
kind: Deployment
metadata:
    name: node-app
    labels:
      foo: bar
spec:
    replicas: 1
    strategy:
      type: Recreate
    selector:
        matchLabels:
            app: node-app    
    template:
        metadata:
            labels:
                app: node-app
                company: teknei
                deploy-fargate: "true"
        spec:
            containers:
            - name: nodeapp
              image: nachomillangarcia/node-app
              ports:
              - containerPort: 3000
              resources:
                requests:
                  cpu: 0.2
                  memory: 128M
                limits:
                  cpu: 0.2
                  memory: 128M
              readinessProbe:
                httpGet:
                  path: /
                  port: 3000
                periodSeconds: 5
              livenessProbe:
                httpGet:
                  path: /
                  port: 3000
                periodSeconds: 30
                initialDelaySeconds: 10
              volumeMounts:
              - name: test
                mountPath: /persistent    
            volumes:
            - name: test
              persistentVolumeClaim:
                claimName: node-app

