apiVersion: v1
kind: Service
metadata:
  name: service-node-app
spec:
  type: LoadBalancer
  selector:
    app: node-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 32334