apiVersion: apps/v1
kind: Deployment
metadata:
    name: todo-app
spec:
    replicas: 2
    selector:
        matchLabels:
            app: todo-app
    template:
        metadata:
            labels:
                app: todo-app
        spec:
            containers:
            - name: java
              image: nachomillangarcia/java-todo-teknei
              ports:
              - containerPort: 8080
              env:
              - name: DB_HOSTNAME
                value: mysql.default.svc.cluster.local
              - name: DB_NAME
                value: todo
              - name: DB_USERNAME
                value: todo
              - name: DB_PASSWORD
                value: pass

---

apiVersion: v1
kind: Service
metadata:
  name: todo-app
spec:
  type: NodePort
  selector:
    app: todo-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080